{nama : Wita Nurjanah}
{npm : 201410059}
{nama program : Biodata}

program biodata;
uses crt;

begin
writeln('********* My Biodata *********');
writeln('nama : Wita Nurjanah');
writeln('npm : 20.14.1.0059');
writeln('alamat : Blok Arjuna Desa Ranjikulon Kecamatan Kasokandel');
writeln('ttl : Majalengka, 10 Maret 2001');
writeln('no.hp : 085524******');
writeln('motto : Lebih baik terlambat daripada tidak sama sekali');

readln;
end.